# pygeoapi configuration for fmedata
# Generated: 2026-03-25T11:15:03.731Z
# Source: postgis

server:
  bind:
    host: 0.0.0.0
    port: ${PORT:-80}
  url: ${PYGEOAPI_SERVER_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  languages:
    - nb-NO
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  limits:
    default_items: 10
    max_items: 10000
  templates:
    path: /pygeoapi/local-templates

logging:
  level: INFO

metadata:
  identification:
    title: fmedata
    description: Dette datasettet inneholder en samling av geografiske soner, utformet for romlig differensiering og forvaltning av områder. Hver sone er beskrevet med et unikt sonenavn (zonename) og en tilhørende sonekategori (zonecategory). Formålet er å tilrettelegge for analyse, planlegging og styring av ulike geografiske områder basert på deres spesifikke klassifisering og funksjon.
    url: https://example.com/dataset
    terms_of_service: https://example.com/terms
    keywords:
      - geospatial
      - data
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Henrik
    email: schhen@kartverket.no
  provider:
    name: Henrik
    organization: Kartverket
    email: schhen@kartverket.no

resources:
  zones:
    type: collection
    title: zones
    description: Spatial collection
    keywords:
      - data
      - zones
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          search_path:
            - ${POSTGRES_SCHEMA}
        id_field: id
        table: zones
        geom_field: geom
        extensions:
          filters:
            - cql2-text
            - cql2-json
            - cql-text

    schema:
      # Resolved properties for zones (Local: 2, Total: 2)
      # Generator Version: 1.0.2
      title: "zones"
      type: object
      properties:
        "waystones_ping":
          title: "Waystones Connection Check"
          type: string
        "zonename":
          title: "Zonename"
          type: string
        "zonecategory":
          title: "Zonecategory"
          type: string

