# pygeoapi configuration for Hospitals2
# Generated: 2026-03-01T19:23:05.078Z
# Source: geopackage

server:
  bind:
    host: 0.0.0.0
    port: 80
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  languages:
    - nb-NO

logging:
  level: INFO

metadata:
  identification:
    title: Hospitals2
    description: Spatial data
    url: https://example.com/dataset
    terms_of_service: https://example.com/terms
    keywords:
      - geospatial
      - data
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Henrik S
    email: hgs716@gmail.com
  provider:
    name: Henrik S
    organization: Megselv
    email: hgs716@gmail.com

resources:
  hospitalpoints:
    type: collection
    title: hospitalpoints
    description: Spatial collection
    extents:
      spatial:
        bbox: [-50553.7180408619, 6468514.74667747, 1076852.81783763, 7863795.19700849]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: SQLiteGPKG
        data: /data/Hospitals2.gpkg
        table: hospitalpoints
        id_field: fid
        geom_field: geom

