app = "sykehus-qgis"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile.qgis"

[env]
  QGIS_SERVER_SERVICE_URL = "https://sykehus-qgis.fly.dev/ows/"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "geodata"
  destination = "/data"
