# pygeoapi configuration for Sykehus
# Generated: 2026-03-29T12:00:23.133Z
# Source: geopackage

server:
  bind:
    host: 0.0.0.0
    port: ${PORT:-80}
  url: ${PYGEOAPI_SERVER_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  languages:
    - nb-NO
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  limits:
    default_items: 10
    max_items: 10000
  templates:
    path: /pygeoapi/local-templates

logging:
  level: INFO

metadata:
  identification:
    title: Sykehus
    description: Dette datasettet inneholder geografiske punktdata som representerer lokasjoner for sykehus. Formålet er å visualisere den romlige fordelingen av helseinstitusjoner, noe som er avgjørende for planlegging av helsetjenester, beredskapsanalyser og studier av tilgjengelighet. Hvert punkt inkluderer sentrale attributter som sykehusets navn, type institusjon, og viktig informasjon om hvorvidt sykehuset har en akuttmottak.
    url: https://example.com/dataset
    terms_of_service: https://example.com/terms
    keywords:
      - sykehus
      - helse
      - helsevesen
      - medisin
      - institusjoner
      - punkter
      - områder
    abstract: Dette datasettet gir geografisk informasjon om sykehus, presentert som punktdata for individuelle lokasjoner og tilhørende geografiske områder. Hovedformålet er å støtte lokalisering, analyse og planlegging av helsetjenester på et nasjonalt eller regionalt nivå. For hvert sykehus inkluderer nøkkelattributter informasjon om sykehusets navn, type og hvorvidt det har et akuttmottak. Dette gir et verdifullt grunnlag for analyser av helsetjenestetilgjengelighet, beredskapsplanlegging og infrastrukturutvikling.
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Henrik Schuller
    email: post@kartverket.no
  provider:
    name: Henrik Schuller
    organization: Kartverket
    email: post@kartverket.no

resources:
  hospitalpoints:
    type: collection
    title: Punkter
    description: Dette datasettet inneholder geografiske punktrepresentasjoner av sykehus og tilhørende arealobjekter. Hvert sykehuspunkt gir detaljer om institusjonens navn, type og om det tilbyr akuttmottak. Arealobjektene kan representere sykehusområder eller tilhørende geografiske regioner. Formålet med datasettet er å fasilitere lokalisering og analyse av helseinstitusjoner basert på deres funksjonalitet og geografiske utbredelse.
    keywords:
      - sykehus
      - helse
      - akuttmottak
      - leger
      - senger
      - helsetjenester
    crs:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
      - http://www.opengis.net/def/crs/EPSG/0/25833
      - http://www.opengis.net/def/crs/EPSG/0/4326
      - http://www.opengis.net/def/crs/EPSG/0/4258
      - http://www.opengis.net/def/crs/EPSG/0/3857
    storageCrs: http://www.opengis.net/def/crs/EPSG/0/25833
    extents:
      spatial:
        bbox: [5.661964614014777, 58.01289713711848, 38.86783938382364, 77.15419161001824]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: SQLiteGPKG
        data: /data/Hospitals.gpkg
        table: hospitalpoints
        id_field: fid
        geom_field: geom
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
        extensions:
          filters:
            - cql2-text
            - cql2-json
            - cql-text

    schema:
      # Resolved properties for hospitalpoints (Local: 33, Total: 33)
      # Generator Version: 1.0.2
      title: "hospitalpoints"
      type: object
      properties:
        "waystones_ping":
          title: "Waystones Connection Check"
          type: string
        "dataset":
          title: "Dataset"
          type: string
        "featuretype":
          title: "FeatureType"
          type: string
        "name":
          title: "Name"
          type: string
        "type":
          title: "Type"
          type: string
        "emergencydepartment":
          title: "EmergencyDepartment"
          type: string
        "doctors":
          title: "Doctors"
          type: number
        "nurses":
          title: "Nurses"
          type: number
        "operationrooms":
          title: "OperationRooms"
          type: number
        "beds":
          title: "Beds"
          type: number
        "employees":
          title: "Employees"
          type: number
        "address":
          title: "Address"
          type: string
        "telephonenumber":
          title: "TelephoneNumber"
          type: number
        "email":
          title: "Email"
          type: string
        "website":
          title: "Website"
          type: string
        "latitude":
          title: "Latitude"
          type: number
        "longitude":
          title: "Longitude"
          type: number
        "mgrs":
          title: "Mgrs"
          type: string
        "classification":
          title: "Classification"
          type: string
        "origin":
          title: "Origin"
          type: string
        "datawithdrawaldate":
          title: "DataWithdrawalDate"
          type: string
          format: date
        "datacapturedate":
          title: "DataCaptureDate"
          type: string
          format: date
        "updatedate":
          title: "UpdateDate"
          type: string
          format: date
        "datasetttype":
          title: "DatasettType"
          type: string
        "gradering":
          title: "Gradering"
          type: string
        "opphav":
          title: "Opphav"
          type: string
        "dgiffeaturealpha":
          title: "DgifFeatureAlpha"
          type: string
        "dgiffeature531":
          title: "DgifFeature531"
          type: string
        "dgifattributealpha":
          title: "DgifAttributeAlpha"
          type: string
        "dgifattribute531":
          title: "DgifAttribute531"
          type: string
        "dgifvaluealpha":
          title: "DgifValueAlpha"
          type: string
        "dgifvalue531":
          title: "DgifValue531"
          type: number
        "dgifccode":
          title: "DgifCCode"
          type: string
        "uuid":
          title: "Uuid"
          type: string

  areas:
    type: collection
    title: Områder
    description: Dette laget inneholder polygoner som representerer definerte geografiske områder.
    keywords:
      - arealer
      - områder
      - geografi
      - romlig
      - datasett
    crs:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
      - http://www.opengis.net/def/crs/EPSG/0/25833
      - http://www.opengis.net/def/crs/EPSG/0/4326
      - http://www.opengis.net/def/crs/EPSG/0/4258
      - http://www.opengis.net/def/crs/EPSG/0/3857
    storageCrs: http://www.opengis.net/def/crs/EPSG/0/25833
    extents:
      spatial:
        bbox: [5.661964614014777, 58.01289713711848, 38.86783938382364, 77.15419161001824]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: SQLiteGPKG
        data: /data/Hospitals.gpkg
        table: areas
        id_field: fid
        geom_field: geom
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
        extensions:
          filters:
            - cql2-text
            - cql2-json
            - cql-text

    schema:
      # Resolved properties for areas (Local: 0, Total: 0)
      # Generator Version: 1.0.2
      title: "areas"
      type: object
      properties:
        "waystones_ping":
          title: "Waystones Connection Check"
          type: string

